### ISSUE TITLE
Error downloading PDF report

### ISSUE THREAD

**Issue by hax3xploit** [1modm/petereport#10]
Facing issues while downloading PDF reports, other formats are working fine.
I'm using dockers.

OS: Kali GNU/Linux
VERSION: 2020.4

![image](https://user-images.githubusercontent.com/24190623/141698503-9a7eae41-9035-4660-9c0e-1e5a666f963b.png)

![image](https://user-images.githubusercontent.com/24190623/141698557-75a669d1-9b8c-4a92-9f8a-3a683da18c13.png)

**Comment by 1modm** [comment]
@hax3xploit it seems a timeout due the amount of data, I did some changes to increase the timeout.

Try to update `git pull` and download again the report.

Thanks

**Comment by hax3xploit** [comment]
Thank you, it worked.
