### ISSUE TITLE
Non-Admin User rights question

### ISSUE THREAD

**Issue by Hax0rG1rl** [1modm/petereport#11]
Heya, 

I've played a little here. It is a clean Django one with the usual pitfalls. 

Here's my pain point. I am trying to define a new non-admin user that should only see/access the products listed under the products category and everything under the Findings section. However, after one hour of testing various combinations, I can't give this user the rights to submit new findings. 

Here's my current rights setup:

![image](https://user-images.githubusercontent.com/3704868/141706106-05f5f73c-6dbe-431e-99a1-ad96b952b88d.png)

![image](https://user-images.githubusercontent.com/3704868/141706124-823efc19-cdfc-4abb-957a-b290666c7b78.png)

By any chance, would I be able to achieve what I am looking after or not quite? 

Thanks again!

**Comment by 1modm** [comment]
@Hax0rG1rl yes you are right Django comes with a built-in permissions system to assign permissions to specific users and groups of users per type of object or object instance. But I customized permissions per role only.

There are by default only 2 roles (administrator and viewer). You can create more if needed, and restrict access in the code, so take a look into views.py and edit the decorator allowed_users with the roles needed.

```
@login_required
@allowed_users(allowed_roles=['administrator'])
```

Also in some templates there are some restrictions per role, for example /templates/home/aside.html:

```
{% if user.groups.all.0|stringformat:'s' == "administrator" %}

          <li class="nav-item">
            <a href="/" class="nav-link">
              <i class="nav-icon fas fa-cogs text-info"></i>
              <p>
                Configuration
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
```

**Comment by Hax0rG1rl** [comment]
Thank you!
