### ISSUE TITLE
Add Search in CWE list while selecting in template Findings

### ISSUE THREAD

**Issue by mvdvaart** [1modm/petereport#14]
Since a few weeks I'm following this project and I've tried a few things now.
In the current version it is not possible to search in CWE list while adding a new template finding.
It would be helpful if the functionality to search in the CWE list, which is present while adding a new finding is available for adding a finding template as well.

I've attached two screenshots.

**Adding a finding _template_ without search functionality within the CWE list.**
![Add finding template](https://user-images.githubusercontent.com/45883753/143680180-ccc3b891-3013-45c2-a54f-b66df0105273.png)

**Adding a finding with functionality to search in the CWE list**
![add finding to report](https://user-images.githubusercontent.com/45883753/143680181-715fb10c-0dea-4af8-93cf-9805431d34a9.png)

**Comment by 1modm** [comment]
@mvdvaart thank you for that I forgot the templates, fixed in 0.3 :)

**Comment by mvdvaart** [comment]
Tested - Solved
