### ISSUE TITLE
Screenshots are not added to the appendix in reports

### ISSUE THREAD

**Issue by mvdvaart** [1modm/petereport#15]
I added a screenshot to a finding in the appendix. But the screenshot and the finding are not shown in reports (PDF and HTML as example). The finding and screenshot could be viewed within PeTeReport.

I've attached screenshots of my test environment, yes with fake data to test.

**All Topics within the Appendix in PeTeReport**
![appendix - overview screenshot](https://user-images.githubusercontent.com/45883753/143680490-5fc33718-def1-4f2c-9b60-b2977dba284c.png)

**Screenshot is shown when the appendex is viewed within PeTeReport**
![appendix - screenshot](https://user-images.githubusercontent.com/45883753/143680491-3535d50e-a731-4e12-b4f9-6ca9df18e432.png)

**In the HTML report the appendix is not present for the Screenshot SQL injection**
![appendix - no screenshot in HTML report](https://user-images.githubusercontent.com/45883753/143680488-8b739b7d-f07d-4416-a6da-e64c335e3d3d.png)

**In the PDFreport the appendix is not present for the Screenshot SQL injection**
![appendix - no screenshot in PDF report](https://user-images.githubusercontent.com/45883753/143680489-a4479903-044d-4dbf-b533-60d45380b9d7.png)

**Comment by mvdvaart** [comment]
Update....

In the old version from 11/Nov/2021 the appendix does work...

see screenshots of my first test environment

PDF report with screenshot in appendix
![old version - appendix](https://user-images.githubusercontent.com/45883753/143683376-6b248efe-6ea7-4895-a888-9ac276dde946.jpg)

HTM report with screenshot in appendix
![old version - appendix - HTM](https://user-images.githubusercontent.com/45883753/143683377-ec92df55-7906-470d-9b31-bc2c4371dbed.jpg)
t

**Comment by 1modm** [comment]
@mvdvaart I think I found the issue, the appendix linked to a finding with None severity was not showed correctly, that should be fixed in 0.5 release. Take a look and let me know. Now Findings (and their Appendix) with severity None are not added to the report.

**Comment by mvdvaart** [comment]
@1modm , I will test it somewhere this weekend. Was a bit busy last week

**Comment by mvdvaart** [comment]
I have tested this in version 0.5 and I have to say sadly it did not work yet..
The screenshots which are added to the appendix related to a finding are not shown in appendix. On the website the appendix is shown..

I've attached some screenshots....





![Appendix 1](https://user-images.githubusercontent.com/45883753/146675415-a50b4724-da05-4a10-9c9b-cfdfd7e46b03.jpg)
![Appendix 2](https://user-images.githubusercontent.com/45883753/146675416-5c3e1b40-ac4f-4c10-9718-1a48a175cdf9.jpg)
![Appendix 3](https://user-images.githubusercontent.com/45883753/146675417-c1904d72-1d74-45a7-aaf5-b9f02a6e353d.jpg)
![Appendix 4](https://user-images.githubusercontent.com/45883753/146675418-e321477e-196e-4020-b6e1-6fc84883673e.jpg)

**Comment by 1modm** [comment]
Solved, found the issue in the appendix generation code. Thanks for reporting!
