### ISSUE TITLE
By default the debug mode is on and shown in the 404 page

### ISSUE THREAD

**Issue by mvdvaart** [1modm/petereport#16]
When I enter a location which does not exist a 404 page is shown to me. This is normal functionality, but in this version a debug mode is shown on screen.

This happens to the version which is directly used after deploying with the docker instructions.

See screenshot for details.
![404 - debug mode](https://user-images.githubusercontent.com/45883753/143681966-195c320a-1bd0-418e-a65b-5473ccdd30fb.PNG)

**Comment by 1modm** [comment]
Hi @mvdvaart thank you for bring this to me, yes you are right Debug mode was enables (I think the application is in early stages so I use to debug errors), if you need to change this take a look into app/config/petereport_config.py and change debug to False:

```
DJANGO_CONFIG = {
	'secret_key': 'django-insecure-key-CHANGEMEPLEASE-pKj9bd9h7*RMCuU',
	'debug': False,
	'admin_module': False,
	'allowed_hosts': '[\'*\']',
	'server_host': 'http://127.0.0.1:8000'
}
```

I will add a note to put this into the documentation and to add 400 and 500 pages

**Comment by 1modm** [comment]
#19
