### ISSUE TITLE
Version build number is not updated, while there was a new version released

### ISSUE THREAD

**Issue by mvdvaart** [1modm/petereport#17]
I've two versions installed in my test environment and the version build number is on both systems 0.1

On the first machine I have a build version 0.1. **On this machine I have no search functionality within the CWE list by adding a new finding to a report.** This machine is from 11/Nov/2021

On the second machine I have a build version 0.1. **On this machine I have the search functionality within the CWE list by adding a new finding to a report.** This machine is from 26/Nov/2021

By using a build number I can related issues to a version (build number) which will improve code quality and it will make communication easier.

---------------------------------------------------------
In the meantime is for example this issue fixed:  https://github.com/1modm/petereport/issues/4

Both versions have the same build number.

----------------------------------------------------------
![version build number](https://user-images.githubusercontent.com/45883753/143682355-a70ebc43-3419-4ee3-95e7-51378754ed3a.PNG)

**Comment by 1modm** [comment]
You are right, I forgot to change the version, I will try to keep an updated changelog. Updated to v0.3

**Comment by mvdvaart** [comment]
Tested - Solved
