### ISSUE TITLE
Error 500 while exporting Report as Jupyter

### ISSUE THREAD

**Issue by mvdvaart** [1modm/petereport#20]
In version 0.3  an Internal server error occurs while exporting the (an existing) report to a Jupyter file.
![Juputer - export](https://user-images.githubusercontent.com/45883753/144073597-32a30254-5a75-45c1-aaf4-da49fb0f5add.PNG)

I'm not sure, but I thought it was happening in version 0.2 as well, but I could not check again since I upgraded on that environment. I know it worked in version 0.1, since I did not know that format and as wondering how it looked like.

`nginx_1       | XXX.XXX.XXX.XXX- - [30/Nov/2021:15:18:57 +0000] "GET /report/download/jupyter/1 HTTP/1.1" 500 145 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0" "-"`

**Comment by 1modm** [comment]
@mvdvaart I think I identified the issue, fixed in version 0.4 https://github.com/1modm/petereport/blob/main/CHANGELOG.md

**Comment by mvdvaart** [comment]
I've tested this in version 0.5... It works!

Thank you
