### ISSUE TITLE
The informational findings are not shown in the graphs

### ISSUE THREAD

**Issue by mvdvaart** [1modm/petereport#21]
In version 0.3, I noticed in the graphs in the reports that informational findings are not taken in count, this is within the web application as well the report itself, for example the PDF. Probably it is fixed as soon as the web application shows the graph correctly.
See screenshots.

Screenshot 1:
![graphs](https://user-images.githubusercontent.com/45883753/144080061-7fbf389e-1b60-4f5c-8f49-2bb7b399f15a.png)
Screenshot 2
![graphs1](https://user-images.githubusercontent.com/45883753/144080864-63fad045-cdae-4f1b-96f1-7a20499dfad5.png)
:

**Comment by 1modm** [comment]
@mvdvaart thanks for that, to be honest that was deliberated, only critical, high, medium, low and info appears in the app, sometimes are findings that are not needed to be reported or are pending to put the final severity. But those findings should not appear also in the report, so I will take a look to address that.

**Comment by 1modm** [comment]
Made some changes in version 0.5 https://github.com/1modm/petereport/blob/main/CHANGELOG.md

I added findings with None severity to the application graphs and removed from the reports. That was the initial intention, to have findings logged into the application but not ready to be reported.

**Comment by mvdvaart** [comment]
I've tested version 0.5.... In this version an informational is added to the report when the CVSS score 0.0 with the severity one is changed to severity Informational.
