### ISSUE TITLE
CVSS Calculator version 3.1

### ISSUE THREAD

**Issue by mvdvaart** [1modm/petereport#22]
Because I'm testing the web application and have already registered some findings, I wasn't sure if I should register such a small finding.

The finding is about a feature that lists CVSS Calculator version 3.1. But the web application uses CVSS Calculator version 3.0.

Now this is not a very big problem, hence my hesitation to report it.

In the source code I've found version 3.0 instead of 3.1
(https://github.com/1modm/petereport/blob/main/app/petereport/static/cvsscalc30.js)

This can also been seen in the web application when you register a finding or in the reports.

To update the calculator I've searched a more recent version (3.1). The CVSS Calculator version 3.1 can be found here:
- https://www.first.org/cvss/calculator/cvsscalc31.js
- https://www.first.org/cvss/calculator/cvsscalc31_helptext.js

A quick solution can also be to change the feature to 3.0   ;-)

**Comment by 1modm** [comment]
@mvdvaart thanks for the links! changed to cvss 3.1 👍 in version 0.4 https://github.com/1modm/petereport/blob/main/CHANGELOG.md

**Comment by mvdvaart** [comment]
Worked! Thanks for updateing. 👍
