### ISSUE TITLE
automatic save

### ISSUE THREAD

**Issue by gpillot** [1modm/petereport#25]
After some time, you need to log in again and you can lose your writing like this. Consequently, I save my job every 10 minutes. After clicking to the button saves, PeteReport quit the edit section. Is it just possible to stay in the edit section instead and that the writing is automatic save?

**Comment by 1modm** [comment]
@gpillot you can control the session timeout modifying the SESSION_COOKIE_AGE value in petereport/app/petereport/settings.py

```
# SESSION AGE 480 Minutes
SESSION_COOKIE_AGE = 480*60
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
```
