### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by meetgyn** [1modm/petereport#30]
I followed manual installation as in the link below, but when I open the page nothing appears. It gets all in white. 
https://1modm.github.io/petereport/django/
![image](https://user-images.githubusercontent.com/3695608/148102576-62bc211b-50ea-4d14-b3fb-ba87204ade88.png)

**Comment by 1modm** [comment]
@meetgyn sorry I forgot to update the documentation: https://1modm.github.io/petereport/django/

`python manage.py runserver 0.0.0.0:8000 --insecure`

**Comment by meetgyn** [comment]
> @meetgyn sorry I forgot to update the documentation: https://1modm.github.io/petereport/django/
> 
> `python manage.py runserver 0.0.0.0:8000 --insecure`

thanks  man,
