### ISSUE TITLE
error to generate PDF report RuntimeError at /report/download/pdf/2  Pandoc died with exitcode "43"

### ISSUE THREAD

**Issue by fellipmelo** [1modm/petereport#31]
RuntimeError at /report/download/pdf/2

Pandoc died with exitcode "43"

Has anyone had this problem or has a solution?

I tried to debug but it didn't work. # #

RuntimeError at /report/download/pdf/2

Pandoc died with exitcode "43" during conversion: b'Error producing PDF.\n! Package inputenc Error: Invalid UTF-8 byte sequence.\n\nSee the inputenc package documentation for explanation.\nType  H <return>  for immediate help.\n ...                                              \n                                                  \nl.598 4- An\xc3\xa1lise e valida\xc3\xa7\xc3\xa3o \n\nTry running pandoc with --pdf-engine=xelatex.\n'

**Comment by 1modm** [comment]
Hi @fellipmelo, yes is a well known issue with pandoc converting UTF-8 chars into PDF, I have found that issue when write text using accents in Spanish or Portuguese. In your case the text `4- An\xc3\xa1lise e valida\xc3\xa7\xc3\xa3o` is causing the issue, try to rewrite without special chars or sometimes what I use to do is to add this as an image.

I will try to find the way to fix that issue asap anyway. 👍

**Comment by fellipmelo** [comment]
Hello friend, first thank you for the timely reply.

I actually changed the way I wrote the text and it worked.

Your software is awesome!
