### ISSUE TITLE
 custom report

### ISSUE THREAD

**Issue by edcarlos-junior** [1modm/petereport#32]
I'm wanting to use a report with my template. Could you give me some guidance on what to do?

**Comment by 1modm** [comment]
@edcarlos-junior can be edited the templates used for each export format, just go to the folder `/app/preport/templates/tpl` and modify the markdown, latex or html as needed.

**Comment by edcarlos-junior** [comment]
hi I want to change the report template in pdf, there I found only md files. I still don't understand how I can change the template.

**Comment by 1modm** [comment]
@edcarlos-junior The PDF is generated with information parsed from the markdown templates, the different objects in the database have each markdown file, in which you can modify the content you need to show, for example the appendix content will contain the field appendix title and description:

```
## {{appendix_in_finding.title|safe}}

{{appendix_in_finding.description|safe}}
```
Then all this content is used by the report template `pdf_report.md` which get all the content and put all together (for example for appendix {{template_appendix}}).

So the markdown files will determine the content.

The PDF format and style is defined in `/app/preport/templates/tpl/petereport.latex`. A LaTeX template which convert the markdown files and content into PDF using pandoc.

For simple customizations like change the color of the title page can be done in `petereport_config.py` for complex style edition you need to edit the latex template `petereport.latex`. The original template can be found here: [https://github.com/Wandmalfarbe/pandoc-latex-template](https://github.com/Wandmalfarbe/pandoc-latex-template)
