### ISSUE TITLE
Import Findings

### ISSUE THREAD

**Issue by mukabhai** [1modm/petereport#33]
Uploading findings in a CSV would be a great option for this tool, We can put a sample CSV, which can be used as a format to upload new findings.
Hopefully we can do this promptly

**Comment by jmorilm** [comment]
@mukabhai 

Hi, in `Upload Findings` you can upload previous CSV exports from other reports.

<img width="715" alt="image" src="https://user-images.githubusercontent.com/90855948/151783487-90fd799e-eb8e-49c3-858d-0711fd17919d.png">

I hope this will cover your needs.

Thanks

**Comment by 1modm** [comment]
@mukabhai 

Hi, in `Upload Findings` you can upload previous CSV exports from other reports.

<img width="715" alt="image" src="https://user-images.githubusercontent.com/90855948/151783487-90fd799e-eb8e-49c3-858d-0711fd17919d.png">

I hope this will cover your needs.

Thanks
