### ISSUE TITLE
Add Search in CWE list while selecting in Findings

### ISSUE THREAD

**Issue by Syntax3r** [1modm/petereport#4]
Hi,

I'm really inspired by this project & overall It's good.
While Add new Finding there's an option to select the CWE from the list but there's no search feature for CWE so a user can easily type and find a particular CWE for the finding. Kindly add this feature in it.

![image](https://user-images.githubusercontent.com/20611131/140407057-a19af8a8-ca94-4c7d-b4b9-8fbe683b2f72.png)

**Comment by 1modm** [comment]
@Syntax3r I think that in the CWE field you write some topic it gives you a match but you are right should be interesting to have.

**Comment by 1modm** [comment]
@Syntax3r done, thank you for your suggestion!

Try to update `git pull` and take a look

**Comment by Syntax3r** [comment]
@1modm I have checked. It's only working by typing the CWE ID (Numeric). It's good if it provides a match by typing the Keywords. 

| **Keyword** | **Matches** |
|--------------|--------------|
| Injection  | SQL Injection, XML Injection, CRLF Injection |

**Comment by 1modm** [comment]
@Syntax3r Which browser are you using? as far as I have checked it worked.

https://user-images.githubusercontent.com/4355335/141460566-ee3d9adb-b0f2-4696-b38f-0a34058760e1.mp4

**Comment by Syntax3r** [comment]
It's working now :) Thanks for the swift response
