### ISSUE TITLE
docker optimization

### ISSUE THREAD

**Issue by noraj** [1modm/petereport#41]
`docker-compose up --build` took me 1 hr 45 min 39 sec (6339 sec): 1 hr 0 min 24 sec (3624 sec) for installing latex and 34 min 35 sec (2075 sec) for exporting the image.

![image](https://user-images.githubusercontent.com/16578570/163735775-e51edf12-7363-4b01-b3ba-7733646d2486.png)

Also the image is heavy

```
$ docker images
REPOSITORY                                                TAG                IMAGE ID       CREATED          SIZE                                                                                                                            
petereport_petereport                                     latest             c7745e0cea28   35 minutes ago   5.19GB
```

It may be possible to accelerate the build time by providing a prebuild docker image on docker hub. For the size maybe the full latex distribution is not required (texlive-most for ArchLinux, texlive-scheme-medium for openSUSE, texlive-latex-recommended texlive-fonts-extra texlive-latex-extra for Ubuntu, etc.).

**Comment by 1modm** [comment]
@noraj thanks, yes you are right most of the latex was not used, I took a look into your OSCP template repositories (thanks again) and reduced the list to `texlive-latex-recommended texlive-fonts-extra texlive-latex-extra p7zip-full texlive-xetex`

`git pull` and try to build again.

Thanks
