### ISSUE TITLE
Add OWASP TOP 10 Security Standards list for WEB, Mobile and API's 

### ISSUE THREAD

**Issue by Syntax3r** [1modm/petereport#5]
Kindly add the list of OWASP Top 10 Security Standard as follows in Add new Findigs:

For API (https://owasp.org/www-project-api-security/)
For Web (https://owasp.org/www-project-top-ten/)
For Mobile (https://owasp.org/www-project-mobile-top-10/)

**Comment by 1modm** [comment]
Very interesting @Syntax3r I will take a look

**Comment by Syntax3r** [comment]
Thanks for a quick response & If you need any help from my side feel free to ping me :)

**Comment by 1modm** [comment]
Added mayor enhancements and contributions. Try to update from the repository `git pull` and try again.

If using docker:

```
git pull
docker compose build --build-arg TARGETARCH=amd64
docker-compose up
```
