### ISSUE TITLE
Failed to fetch

### ISSUE THREAD

**Issue by Shiva108** [1modm/petereport#52]
Im on parrot linux. Doing so: 
`docker-compose build --build-arg TARGETARCH=amd64`
Results in failed to fetch:
`E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/a/apt/libapt-pkg6.0_2.0.8_amd64.deb  404  Not Found [IP: 91.189.91.39 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/a/apt/apt_2.0.8_amd64.deb  404  Not Found [IP: 91.189.91.39 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
ERROR: Service 'petereport' failed to build: The command '/bin/sh -c apt-get -y upgrade' returned a non-zero code: 100`
Visiting the links above I can see that the files are actually missing on the server.
Please advice.

**Comment by luminescence69** [comment]
I'm getting the same error as well, is there any workaround for this?

**Comment by Shiva108** [comment]
> I'm getting the same error as well, is there any workaround for this?

I havent got any feedback from dev sadly.

**Comment by 1modm** [comment]
As indicated in the error (`404 Not Found`), it seems to be a connectivity issue on your side trying to fetch from `archive.ubuntu.com`.

Anyway I have done a fresh deploy in parrot and worked fine.

Thanks
