### ISSUE TITLE
French Traduction Proposal

### ISSUE THREAD

**Issue by Rog9741** [1modm/petereport#59]
Hi, this is not an issue but i'd like to help for a French traduction of your tool, not that good in code but i'll try to create one and give it to you after if you are intrested

**Comment by 1modm** [comment]
@Rog9741 thanks for the idea, I have pending to implement the multilingual option https://github.com/1modm/petereport/issues/42.

If you are looking only to translate your output templates you can do it editing the files in preport/templates/tpl/

**Comment by 1modm** [comment]
Added Multilingual and Internationalization support.

You can translate to French editing the po file in https://github.com/1modm/petereport/blob/main/app/locale/fr/LC_MESSAGES/django.po
