### ISSUE TITLE
Where click generate pdf report error 

### ISSUE THREAD

**Issue by fellipmelo** [1modm/petereport#6]
where i generate Report in all formats, return error

`<h1>RuntimeError
       at /report/download/pdf/3</h1>
  <pre class="exception_value">Pandoc died with exitcode "1" during conversion: b'pandoc: /opt/petereport/app/storage_reports/pdf/PEN-PDF_aaaaa_202111042217.pdf: openBinaryFile: does not exist (No such file or directory)\n'</pre>
  

Request Method: | GET
-- | --
http://127.0.0.1/report/download/pdf/3
3.2.5
RuntimeError
Pandoc died with exitcode "1" during conversion: b'pandoc: /opt/petereport/app/storage_reports/pdf/PEN-PDF_aaaaa_202111042217.pdf: openBinaryFile: does not exist (No such file or directory)\n'
/usr/local/lib/python3.8/dist-packages/pypandoc/__init__.py, line 321, in _convert_input
/usr/bin/python3
3.8.10
['/opt/petereport/app',  '/opt/petereport',  '/usr/bin',  '/usr/lib/python38.zip',  '/usr/lib/python3.8',  '/usr/lib/python3.8/lib-dynload',  '/usr/local/lib/python3.8/dist-packages',  '/usr/lib/python3/dist-packages']
Thu, 04 Nov 2021 22:18:03 +0000

`

How i solv this is ?

**Comment by 1modm** [comment]
Hi @fellipmelo sorry I fixed today, just realized that the folders were not in the repo. To fix the issue just:

1- stop the server or docker
2- execute: git pull
3- start the server or docker
