### ISSUE TITLE
Import Findiings

### ISSUE THREAD

**Issue by matholiveira91** [1modm/petereport#62]
I had problems to import a findings csv to a report, and i have another problem i have a lot of hosts and a lot of  vulnerabilities to manage, add then one by one manually i'll take me a lot of time. When i try to import a csv filie with a set of vulnerabilities i receive HTTP 500 error

**Comment by ramsal** [comment]
Same error when I generate PDF report
![imagen](https://user-images.githubusercontent.com/9681847/200440779-76c61f0d-d254-43cd-b39d-cd6760be669a.png)

**Comment by ramsal** [comment]
> Same error when I generate PDF report ![imagen](https://user-images.githubusercontent.com/9681847/200440779-76c61f0d-d254-43cd-b39d-cd6760be669a.png)

Solved! I config debug true and detect special characters in my description

**Comment by 1modm** [comment]
@ramsal thanks for the update, do you know which character was causing the issue? I would like to take a look.

Thanks!

**Comment by ramsal** [comment]
> @ramsal thanks for the update, do you know which character was causing the issue? I would like to take a look.
> 
> Thanks!
this  ☒

**Comment by 1modm** [comment]
@ramsal Found the issue, some unicode chars have problems with pandoc and latex. To fix the issue you can add to the line 985 the next option:` '--pdf-engine', 'xelatex'` :

`    output_pypandoc = pypandoc.convert_text(final_markdown_output, to='pdf', outputfile=pdf_file_output, format='md', extra_args=['-H', PDF_HEADER_FILE, '--from', 'markdown+yaml_metadata_block+raw_html', '--template', PETEREPORT_LATEX_FILE, '--table-of-contents', '--toc-depth', '4', '--number-sections', '--highlight-style', 'breezedark', '--filter', 'pandoc-latex-environment', '--listings', '--pdf-engine', 'xelatex'])`

**Comment by ramsal** [comment]
> 

Thanks! Regards!

**Comment by 1modm** [comment]
@matholiveira91 Hi, I did some updates, could you try?

First update https://1modm.github.io/petereport/django/#upgrade-petereport

If doesn't works enable debug mode in `app/config/petereport_config.py `and attach here the output

**Comment by 410-sh** [comment]
When trying to upload findings from a csv file, I am still getting a 500 error. Below is the output I am getting with debug mode enabled:
```
Request URL: http://localhost/en/findings/upload/1

Django Version: 4.2.6
Python Version: 3.11.2
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'martor',
 'django_bleach',
 'preport']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/petereport-_1hU1HQ3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/virtualenvs/petereport-_1hU1HQ3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/virtualenvs/petereport-_1hU1HQ3/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/petereport/app/preport/decorators.py", line 14, in wrapper_func
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/petereport/app/preport/views.py", line 1590, in upload_csv_findings
    f_id = header.index("ID")
           ^^^^^^^^^^^^^^^^^^

Exception Type: ValueError at /en/findings/upload/1
Exception Value: 'ID' is not in list
```

If I comment out one line, it seems to throw the same error for the next line

![image](https://github.com/1modm/petereport/assets/85971872/3664137b-cc1f-40bb-9fe5-80ec4fe3f5f9)
