### ISSUE TITLE
Feature to select specific findings only from a product in DefectDojo

### ISSUE THREAD

**Issue by 1modm** [1modm/petereport#64]

**Comment by surajanuja** [comment]
@1modm Appreciate your effort in taking up this request as an enhancement. So just out of curiosity I am asking, is there any tentative timeline that you have in mind to make this change?

**Comment by 1modm** [comment]
Done :) https://github.com/1modm/petereport/commit/9ece28cba8b41f5c3bca4293428c2022cc337292

git pull and take a look

**Comment by surajanuja** [comment]
@1modm - This feature is completely working fine but only shows up 25 products. But in my case I have more then 100 products - So the pending product list is not showing up. 

But the first 25 products looks good and I can individually add the findings. If you can add option to select multiple findings and then import from a product then that will also be good

**Comment by 1modm** [comment]
@surajanuja done, was a limit of products set by default to 25. You should see all the products now. I will explore in the multiple selection option.
