### ISSUE TITLE
PDF export format giving 500 error

### ISSUE THREAD

**Issue by pswalia2u** [1modm/petereport#65]
![image](https://user-images.githubusercontent.com/20887270/213727733-af0af48f-752e-4ef5-b758-30ffbe2e1ab1.png)

**Comment by surajanuja** [comment]
@1modm Even I am getting this same error on latest 1.3.3. Even when I export html report for the findings imported from DefectDojo. The image in the finding does not loads up. 
![image](https://user-images.githubusercontent.com/112088960/213733152-a44c9612-8089-4730-9553-32fda5f9ef23.png)

**Comment by 1modm** [comment]
@pswalia2u Could you enable the debug mode and attach the output?

in petereport_config.py:
`'debug': True,`

@surajanuja Could you check the source of the image? what data was exported? is an URL or the image in base64 format?

Thanks

**Comment by pswalia2u** [comment]
Hi @1modm , I have enabled debug mode. Where will i get the debug output? I am using docker . Thanks

**Comment by pswalia2u** [comment]
Got it. Here is the output 
[debug_petereport.pdf](https://github.com/1modm/petereport/files/10473030/debug_petereport.pdf)
![Untitled](https://user-images.githubusercontent.com/20887270/213886610-513fd53d-7cf4-43eb-91ce-0de4c3bc1a20.png)

**Comment by pswalia2u** [comment]
Hi, Is anyone able to find a fix for this?

**Comment by 1modm** [comment]
@pswalia2u it seems that happens when the size the table is bigger than the width of the column. The next couple of lines appear in the latex output once the above condition is triggered. The application used to generate the PDF has still an opened issue about that: https://github.com/jgm/pandoc/issues/1023
