### ISSUE TITLE
Lang files

### ISSUE THREAD

**Issue by TheQmaks** [1modm/petereport#7]
Hi, can you add lang files for translation?

**Comment by 1modm** [comment]
@TheQmaks thanks for the suggestion, nice feature to have, added to the feature list 👍

**Comment by alacerda** [comment]
@1modm I wanna help with that feature. How can we track that to avoid double work on the same issue? Once I've finished I'll push a PR.

**Comment by 1modm** [comment]
@alacerda thanks for the help, yes sure will be very useful, for me the first step is how to manage lang files in django, then we can focus in the templates to include the fields to translate.

What I can do is another branch and then merge to the main one. 

https://github.com/1modm/petereport/tree/translation

Thanks

**Comment by 1modm** [comment]
Added Multilingual and Internationalization support.

You can translate to French editing the po file in https://github.com/1modm/petereport/blob/main/app/locale/fr/LC_MESSAGES/django.po
