### ISSUE TITLE
unicode pdf generation failed due to "43" exitcode after enable '--pdf-engine', 'xelatex'

### ISSUE THREAD

**Issue by 50YUD4N60** [1modm/petereport#71]
exitcode "43" After enabled '--pdf-engine', 'xelatex'

I just commet line 937 & uncomment line 938, wondering if there's a way to fix it?

Internal Server Error: /en/report/download/pdf/8
petereport_1  | Traceback (most recent call last):
petereport_1  |   File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
petereport_1  |     response = get_response(request)
petereport_1  |   File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 181, in _get_response
petereport_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
petereport_1  |   File "/usr/local/lib/python3.8/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
petereport_1  |     return view_func(request, *args, **kwargs)
petereport_1  |   File "/opt/petereport/app/preport/views.py", line 938, in reportdownloadpdf
petereport_1  |     output_pypandoc = pypandoc.convert_text(final_markdown_output, to='pdf', outputfile=pdf_file_output, format='md', extra_args=['-H', PDF_HEADER_FILE, '--from', 'markdown+yaml_metadata_block+raw_html', '--template', PETEREPORT_LATEX_FILE, '--table-of-contents', '--toc-depth', '4', '--number-sections', '--highlight-style', 'breezedark', '--filter', 'pandoc-latex-environment', '--listings', '--pdf-engine', 'xelatex'])
petereport_1  |   File "/usr/local/lib/python3.8/dist-packages/pypandoc/__init__.py", line 91, in convert_text
petereport_1  |     return _convert_input(source, format, 'string', to, extra_args=extra_args,
petereport_1  |   File "/usr/local/lib/python3.8/dist-packages/pypandoc/__init__.py", line 426, in _convert_input
petereport_1  |     raise RuntimeError(
petereport_1  | RuntimeError: Pandoc died with exitcode "43" during conversion: Error producing PDF.
petereport_1  | ! Argument of \str_uppercase:n has an extra }.
petereport_1  | <inserted text>
petereport_1  |                 \par
petereport_1  | l.211   \setmainlanguage[]{}

**Comment by 1modm** [comment]
Added mayor enhancements and contributions. Try to update from the repository `git pull` and try again.

If using docker:

```
git pull
docker compose build --build-arg TARGETARCH=amd64
docker-compose up
```
