### ISSUE TITLE
ImportError during Docker build 

### ISSUE THREAD

**Issue by FullStackSandwich** [1modm/petereport#74]
petereport_1  | Installing dependencies from Pipfile.lock (21d328)…
petereport_1  | asgiref==3.7.2
petereport_1  | backports.zoneinfo==0.2.1
petereport_1  | bleach==5.0.1
petereport_1  | blinker==1.4
petereport_1  | cairocffi==1.6.0
petereport_1  | CairoSVG==2.7.0
petereport_1  | certifi==2023.5.7
petereport_1  | cffi==1.15.1
petereport_1  | charset-normalizer==3.2.0
petereport_1  | cryptography==3.4.8
petereport_1  | cssselect2==0.7.0
petereport_1  | dbus-python==1.2.18
petereport_1  | defusedxml==0.7.1
petereport_1  | distlib==0.3.4
petereport_1  | distro==1.7.0
petereport_1  | distro-info===1.1build1
petereport_1  | Django==4.2.3
petereport_1  | django-bleach==3.0.0
petereport_1  | filelock==3.6.0
petereport_1  | gunicorn==20.1.0
petereport_1  | httplib2==0.20.2
petereport_1  | idna==3.4
petereport_1  | importlib-metadata==4.6.4
petereport_1  | jeepney==0.7.1
petereport_1  | keyring==23.5.0
petereport_1  | launchpadlib==1.10.16
petereport_1  | lazr.restfulclient==0.14.4
petereport_1  | lazr.uri==1.0.6
petereport_1  | Markdown==3.3.4
petereport_1  | martor==1.6.15
petereport_1  | more-itertools==8.10.0
petereport_1  | oauthlib==3.2.0
petereport_1  | pandoc-latex-environment==1.1.6
petereport_1  | pandocfilters==1.5.0
petereport_1  | Pillow==10.0.0
petereport_1  | pipenv==11.9.0
petereport_1  | platformdirs==2.5.1
petereport_1  | pycparser==2.21
petereport_1  | PyGObject==3.42.1
petereport_1  | PyJWT==2.3.0
petereport_1  | pypandoc==1.11
petereport_1  | pyparsing==2.4.7
petereport_1  | python-apt==2.4.0+ubuntu1
petereport_1  | requests==2.31.0
petereport_1  | SecretStorage==3.3.1
petereport_1  | six==1.16.0
petereport_1  | sqlparse==0.4.4
petereport_1  | termcolor==1.1.0
petereport_1  | tinycss2==1.1.1
petereport_1  | typing_extensions==4.7.1
petereport_1  | unattended-upgrades==0.1
petereport_1  | urllib3==2.0.4
petereport_1  | virtualenv==20.13.0+ds
petereport_1  | virtualenv-clone==0.3.0
petereport_1  | wadllib==1.3.6
petereport_1  | webencodings==0.5.1
petereport_1  | zipp==1.0.0
petereport_1  | Traceback (most recent call last):
petereport_1  |   File "./app/manage.py", line 11, in main
petereport_1  |     from django.core.management import execute_from_command_line
petereport_1  |   File "/root/.local/share/virtualenvs/petereport-_1hU1HQ3/lib/python3.8/site-packages/django/core/management/__init__.py", line 16, in <module>
petereport_1  |     from django.apps import apps
petereport_1  |   File "/root/.local/share/virtualenvs/petereport-_1hU1HQ3/lib/python3.8/site-packages/django/apps/__init__.py", line 1, in <module>
petereport_1  |     from .config import AppConfig
petereport_1  |   File "/root/.local/share/virtualenvs/petereport-_1hU1HQ3/lib/python3.8/site-packages/django/apps/config.py", line 13, in <module>
petereport_1  |     class AppConfig:
petereport_1  |   File "/root/.local/share/virtualenvs/petereport-_1hU1HQ3/lib/python3.8/site-packages/django/apps/config.py", line 62, in AppConfig
petereport_1  |     def default_auto_field(self):
petereport_1  |   File "/root/.local/share/virtualenvs/petereport-_1hU1HQ3/lib/python3.8/site-packages/django/utils/functional.py", line 27, in __init__
petereport_1  |     from django.utils.deprecation import RemovedInDjango50Warning
petereport_1  |   File "/root/.local/share/virtualenvs/petereport-_1hU1HQ3/lib/python3.8/site-packages/django/utils/deprecation.py", line 4, in <module>
petereport_1  |     from asgiref.sync import iscoroutinefunction, markcoroutinefunction, sync_to_async
petereport_1  |   File "/root/.local/share/virtualenvs/petereport-_1hU1HQ3/lib/python3.8/site-packages/asgiref/sync.py", line 27, in <module>
petereport_1  |     from .current_thread_executor import CurrentThreadExecutor
petereport_1  |   File "/root/.local/share/virtualenvs/petereport-_1hU1HQ3/lib/python3.8/site-packages/asgiref/current_thread_executor.py", line 10, in <module>
petereport_1  |     from typing_extensions import ParamSpec
petereport_1  | ModuleNotFoundError: No module named 'typing_extensions'
petereport_1  | 
petereport_1  | The above exception was the direct cause of the following exception:
petereport_1  | 
petereport_1  | Traceback (most recent call last):
petereport_1  |   File "./app/manage.py", line 22, in <module>
petereport_1  |     main()
petereport_1  |   File "./app/manage.py", line 13, in main
petereport_1  |     raise ImportError(
petereport_1  | ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

I get the same error using Django as well. I'm using Kali Linux

**Comment by 1modm** [comment]
Added mayor enhancements and contributions. Try to update from the repository `git pull` and try again.

If using docker:

```
git pull
docker compose build --build-arg TARGETARCH=amd64
docker-compose up
```
