### ISSUE TITLE
Upload Image error 500

### ISSUE THREAD

**Issue by Aledangelo** [1modm/petereport#79]
I'm using PeteReport 1.4.0 . When I try to upload an image via the upload form, nothing loads in the result textboxes.
This "Internal Server Error" message appears in the logs, but I don't know how to fix it.

```
petereport_nginx   |   172.18.0.1 -  - [11/Sep/2023:23:49:15  +0000]  "POST /martor/api/uploader/ HTTP/1.1" 500 145 "https://127.0.0.1/en/finding/edit/3" "Mozzilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/117.0" "-"
```

**Comment by 1modm** [comment]
@Aledangelo  Fixed in the last commit, was an issue with a thirdparty component
