### ISSUE TITLE
 error downloading report

### ISSUE THREAD

**Issue by edcarlos-junior** [1modm/petereport#8]
when I go to download the report it always has an error
RuntimeError at /report/download/pdf/1
Pandoc died with exitcode "1" during conversion: b'pandoc: /home/nois/petereport/app/preport/templates/tpl/pdf/pdf_header.tex: openBinaryFile: does not exist (No such file or directory)\n
however the directory exists. Any solution ?

**Comment by 1modm** [comment]
Hi, are you using docker or running django directly?

**Comment by edcarlos-junior** [comment]
> Olá, você está usando o docker ou executando o django diretamente?

I'm using docker

**Comment by 1modm** [comment]
Hi @edcarlos-junior it should work, try to do a pull: `git pull` and then run docker again. if doesn't work let me know which OS are you using and I will try to replicate the issue

**Comment by edcarlos-junior** [comment]
> Olá @ edcarlos-junior , deve funcionar, tente fazer um pull: `git pull`e execute o docker novamente. se não funcionar, me diga qual sistema operacional você está usando e tentarei replicar o problema

not solved. I redid the installation in kali linux and now it's in another error.
![Captura de tela_2021-11-11_13-24-00](https://user-images.githubusercontent.com/88686623/141332803-55258dcb-d7a2-475d-a6c4-45adcca8fc42.png)
I'm using kali linux. I found the project interesting and it's what I'm really needing at the moment at work, so if you can help me, I'm very grateful.

**Comment by 1modm** [comment]
I think I found the issue, the first error was because Docker (Dockerfile) workdir is set to: `WORKDIR /opt/petereport` and you was using `/home/nois/`

The second error is because pandoc with latex is not able to handle unicode and special chars, so my suggestion is to put the evidence "Esses ataques ....." in a picture or remove non utf-8 chars.

**Comment by edcarlos-junior** [comment]
I added some dependencies and changed the directory to opt and it worked at least now it is generating html report. thanks for the support.
