### ISSUE TITLE
Option to scale images

### ISSUE THREAD

**Issue by Moneysac90** [1modm/petereport#88]
It would be awesome to have a scaling option for images. Currently the syntax `![](https://some_url)` is used do include images. It would be great to include an additional parameter to scale images or to set the image width/height. 

For example: 
```![](https://some_url){height=10cm}```  Set height to 10cm.
or  
```![](https://some_url){scale=80%}``` Scale image to 80% of its original size.

**Comment by 1modm** [comment]
You can use markdown to do it, for example:

![test](https://petereport.mpsec.eu/media/images/company_picture.png){width=20%}
![test](https://petereport.mpsec.eu/media/images/company_picture.png){:height="36px" width="36px"}
