### ISSUE TITLE
Is there a way to add a valid TLS cert to the server?

### ISSUE THREAD

**Issue by Hax0rG1rl** [1modm/petereport#9]
Hey, 

Thanks for this. Is there any way to add a valid TLS cert, Letsencrypt, etc., to the server? 

Thank you!

**Comment by 1modm** [comment]
Hi @Hax0rG1rl 

Yes sure, take a look into the nginx folder, there you can find the webserver configuration file and the default certificates, change the location or replace them with your own certificates.

https://github.com/1modm/petereport/tree/main/nginx

petereport.conf:

`
ssl_certificate /opt/petereport/nginx/petereport.crt;

ssl_certificate_key /opt/petereport/nginx/petereport.key;
`
