### ISSUE TITLE
i want to remove petereport logo from footer of front page  

### ISSUE THREAD

**Issue by arijitdirghanji** [1modm/petereport#91]
I want remove this, kindly help me

![image](https://github.com/1modm/petereport/assets/50274322/228de071-873c-4b51-aaf4-fc7ae3b7c9c5)

**Comment by 1modm** [comment]
Hi,

You just can take a look into the config file **petereport_config.py**, the logo it is in the file title.png:
![image](https://github.com/1modm/petereport/assets/4355335/31f1b299-aeab-4828-8d8e-e353e1ad94c4)

And adjust the location of the image, or just edit and add your logo in title.png: https://github.com/1modm/petereport/blob/main/app/preport/templates/tpl/pdf/default/title.png
